name: PurpleSpawner
version: '${project.version}'
main: de.relativv.purplespawner.main.PurpleSpawner
api-version: 1.17
authors: [ relativv ]
description: A custom spawner plugin

commands:
  spawnergive:
    description: Give customized spawners
